/*
 * Copyright (c) 2026 Jason Crawford
 * SPDX-License-Identifier: AGPL-3.0-only
 *
 * XEdDSA cross-validation and oracle-vector tests.
 *
 *   1. Cross-validation (always runs, no external data): the Edwards public
 *      key A produced by the sign path (gy_xeddsa_calculate_key_pair) must
 *      equal the one produced by the verify path's Montgomery-to-Edwards map
 *      (monocypher crypto_x25519_to_eddsa).
 *   2. Oracle KATs (runs when tests/vectors/xeddsa_libsignal.vec is present):
 *      byte-exact reproduction of libsignal's XEdDSA signatures via
 *      gy_xeddsa_sign_z, acceptance by gy_xeddsa_verify, and rejection of the
 *      invalid verify cases.  See docs/TEST_ORACLES.md and
 *      tools/oracles/xeddsa_libsignal/.
 *
 * The vector file is generated by an AGPL libsignal oracle and checked in; it
 * is never linked or ported (geryon's licensing boundary).
 */

#include <monocypher.h>

#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "ed25519.h"
#include "error.h"
#include "util.h"
#include "x25519.h"

#include "gy_test.h"

#define VEC_PATH GERYON_TEST_SOURCE_DIR "/tests/vectors/xeddsa_libsignal.vec"
#define MAX_MSG_HEX (2 * GY_XEDDSA_MAX_MSG + 64)

TEST(crossvalidate_sign_vs_verify_pubkey)
{
    uint8_t mont_pk[32], mont_sk[32], ed_sign[32], ed_verify[32], a[32];
    int t;

    /* For many fresh keys, the sign-path A equals the verify-path A. */
    for (t = 0; t < 64; t++) {
        ASSERT_EQ(gy_x25519_keypair(mont_pk, mont_sk), GY_OK);
        ASSERT_EQ(gy_xeddsa_calculate_key_pair(ed_sign, a, mont_sk), GY_OK);
        crypto_x25519_to_eddsa(ed_verify, mont_pk);
        ASSERT_MEMEQ(ed_sign, ed_verify, 32);
    }
}

/* One parsed vector record. */
struct rec {
    uint8_t sk[32], pk[32], z[64], sig[64];
    uint8_t msg[GY_XEDDSA_MAX_MSG];
    size_t msg_len;
    int has_sk, has_pk, has_z, has_sig, has_valid, valid;
};

static void
rec_clear(struct rec *r)
{
    memset(r, 0, sizeof(*r));
}

/* Apply one "key=hexvalue" line to the record being assembled. */
static void
rec_field(struct rec *r, const char *line)
{
    const char *eq = strchr(line, '=');
    const char *val;
    uint8_t tmp[1];

    if (eq == NULL)
        return;
    val = eq + 1;
    if (strncmp(line, "sk=", 3) == 0)
        r->has_sk = gy_hex_decode(r->sk, 32, val) == 32;
    else if (strncmp(line, "pk=", 3) == 0)
        r->has_pk = gy_hex_decode(r->pk, 32, val) == 32;
    else if (strncmp(line, "z=", 2) == 0)
        r->has_z = gy_hex_decode(r->z, 64, val) == 64;
    else if (strncmp(line, "sig=", 4) == 0)
        r->has_sig = gy_hex_decode(r->sig, 64, val) == 64;
    else if (strncmp(line, "msg=", 4) == 0) {
        int n = gy_hex_decode(r->msg, sizeof(r->msg), val);
        r->msg_len = n < 0 ? 0 : (size_t)n;
    } else if (strncmp(line, "valid=", 6) == 0) {
        r->has_valid = gy_hex_decode(tmp, 1, val) == 1;
        r->valid = r->has_valid && tmp[0] != 0;
    }
}

/* Check one assembled record; returns the number of assertions exercised. */
static void
rec_check(const struct rec *r)
{
    uint8_t sig[64];

    /*
     * Defensive: skip any sign-bit-1 record (D-XED-11).  libsignal stores A's
     * sign bit in s bit 255 for such keys; geryon follows the paper (canonical
     * s) and agrees only for sign-bit-0 keys, which is all the oracle emits.
     * s is the second half, so the flag is sig[63].  Skip valid records whose
     * s carries the bit; corrupted (invalid) verify records keep a clear bit.
     */
    if (r->has_sig && (r->sig[63] & 0x80) && !(r->has_valid && !r->valid))
        return;

    if (r->has_sk && r->has_z && r->has_sig) {
        /* Sign KAT: reproduce the oracle signature byte-exact. */
        ASSERT_EQ(gy_xeddsa_sign_z(sig, r->sk, r->msg, r->msg_len, r->z),
                  GY_OK);
        ASSERT_MEMEQ(sig, r->sig, 64);
        if (r->has_pk)
            ASSERT_EQ(gy_xeddsa_verify(r->sig, r->pk, r->msg, r->msg_len),
                      GY_OK);
    } else if (r->has_pk && r->has_sig && r->has_valid) {
        /* Verify KAT: accept valid, reject invalid. */
        int rc = gy_xeddsa_verify(r->sig, r->pk, r->msg, r->msg_len);
        ASSERT_EQ(rc, r->valid ? GY_OK : GY_ERR_VERIFY);
    }
}

TEST(libsignal_oracle_vectors)
{
    static char line[MAX_MSG_HEX + 16];
    struct rec r;
    FILE *f;
    int count = 0;

    f = fopen(VEC_PATH, "r");
    if (f == NULL) {
        printf("  (no %s; run tools/oracles/xeddsa_libsignal to generate)\n",
               "tests/vectors/xeddsa_libsignal.vec");
        return;
    }

    rec_clear(&r);
    while (gy_read_line(f, line, sizeof(line))) {
        if (line[0] == '\0') {
            rec_check(&r);
            rec_clear(&r);
            count++;
        } else if (line[0] != '#') {
            rec_field(&r, line);
        }
    }
    /* Trailing record with no final blank line. */
    if (r.has_sk || r.has_pk) {
        rec_check(&r);
        count++;
    }
    fclose(f);
    ASSERT_TRUE(count > 0, "oracle vector file contained records");
}

int
main(void)
{
    if (gy_core_init() != GY_OK)
        return 1;

    {
        static const struct gy_test_case cases[] = {
            GY_TEST(crossvalidate_sign_vs_verify_pubkey),
            GY_TEST(libsignal_oracle_vectors),
        };
        return gy_test_run(cases, sizeof(cases) / sizeof(cases[0]));
    }
}
