/*
 * Copyright (c) 2026 Jason Crawford
 * SPDX-License-Identifier: AGPL-3.0-only
 *
 * X3DH DH-stage oracle vectors (D-GEN-6).  Cross-checks geryon's
 * X3DH Diffie-Hellman stage (DH1..DH4, the X3DH specification, section 3) against libsignal's
 * X25519: for each synthetic handshake the descriptor dh op over the spec
 * pairing must reproduce the oracle's agreement.
 *
 * libsignal cannot emit the assembled SK or its KDF info string (see
 * docs/TEST_ORACLES.md and tools/oracles/x3dh_libsignal/), so the SK / F /
 * salt / HKDF / info composition is NOT checked here; it stays covered by the
 * F-guard KAT and self-vectors in tests/kex/test_x3dh.c.  The vector file is
 * generated by an AGPL oracle and checked in; it is never linked or ported.
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "encode.h"
#include "error.h"
#include "suite.h"
#include "util.h"

#include "gy_test.h"

#define VEC_PATH GERYON_TEST_SOURCE_DIR "/tests/vectors/x3dh_libsignal.vec"

static const struct gy_suite_desc *D;

struct rec {
    uint8_t ik_a_sk[32], ek_a_sk[32];
    uint8_t ik_b_pk[32], spk_b_pk[32], opk_b_pk[32];
    uint8_t dh1[32], dh2[32], dh3[32], dh4[32];
    int opk;
};

static void
rec_field(struct rec *r, const char *line)
{
    const char *eq = strchr(line, '=');
    const char *val;
    uint8_t tmp[1];

    if (eq == NULL)
        return;
    val = eq + 1;
    if (strncmp(line, "ik_a_sk=", 8) == 0)
        gy_hex_decode(r->ik_a_sk, 32, val);
    else if (strncmp(line, "ek_a_sk=", 8) == 0)
        gy_hex_decode(r->ek_a_sk, 32, val);
    else if (strncmp(line, "ik_b_pk=", 8) == 0)
        gy_hex_decode(r->ik_b_pk, 32, val);
    else if (strncmp(line, "spk_b_pk=", 9) == 0)
        gy_hex_decode(r->spk_b_pk, 32, val);
    else if (strncmp(line, "opk_b_pk=", 9) == 0)
        gy_hex_decode(r->opk_b_pk, 32, val);
    else if (strncmp(line, "dh1=", 4) == 0)
        gy_hex_decode(r->dh1, 32, val);
    else if (strncmp(line, "dh2=", 4) == 0)
        gy_hex_decode(r->dh2, 32, val);
    else if (strncmp(line, "dh3=", 4) == 0)
        gy_hex_decode(r->dh3, 32, val);
    else if (strncmp(line, "dh4=", 4) == 0)
        gy_hex_decode(r->dh4, 32, val);
    else if (strncmp(line, "opk=", 4) == 0) {
        if (gy_hex_decode(tmp, 1, val) == 1)
            r->opk = tmp[0] != 0;
    }
}

static void
rec_check(const struct rec *r)
{
    uint8_t out[GY_DH_MAX];

    /* DH1 = DH(IK_A, SPK_B). */
    ASSERT_EQ(D->dh(out, r->ik_a_sk, r->spk_b_pk), GY_OK);
    ASSERT_MEMEQ(out, r->dh1, 32);
    /* DH2 = DH(EK_A, IK_B). */
    ASSERT_EQ(D->dh(out, r->ek_a_sk, r->ik_b_pk), GY_OK);
    ASSERT_MEMEQ(out, r->dh2, 32);
    /* DH3 = DH(EK_A, SPK_B). */
    ASSERT_EQ(D->dh(out, r->ek_a_sk, r->spk_b_pk), GY_OK);
    ASSERT_MEMEQ(out, r->dh3, 32);
    /* DH4 = DH(EK_A, OPK_B), only when an OPK is present. */
    if (r->opk) {
        ASSERT_EQ(D->dh(out, r->ek_a_sk, r->opk_b_pk), GY_OK);
        ASSERT_MEMEQ(out, r->dh4, 32);
    }
}

TEST(x3dh_dh_stage_vectors)
{
    static char line[256];
    struct rec r;
    FILE *f;
    int count = 0;

    f = fopen(VEC_PATH, "r");
    if (f == NULL) {
        printf("  (no %s; run tools/oracles/x3dh_libsignal to generate)\n",
               "tests/vectors/x3dh_libsignal.vec");
        return;
    }

    memset(&r, 0, sizeof(r));
    while (gy_read_line(f, line, sizeof(line))) {
        if (line[0] == '\0') {
            rec_check(&r);
            memset(&r, 0, sizeof(r));
            count++;
        } else if (line[0] != '#') {
            rec_field(&r, line);
        }
    }
    fclose(f);
    ASSERT_TRUE(count > 0, "oracle vector file contained records");
}

int
main(void)
{
    if (gy_core_init() != GY_OK)
        return 1;
    D = gy_suite_desc(GY_SUITE_C25519);
    if (D == NULL)
        return 1;

    {
        static const struct gy_test_case cases[] = {
            GY_TEST(x3dh_dh_stage_vectors),
        };
        return gy_test_run(cases, sizeof(cases) / sizeof(cases[0]));
    }
}
